version: '3.4'

services:
  cko.paymentgateway.api:
    image: ${DOCKER_REGISTRY-}ckopaymentgatewayapi
    build:
      context: .
      dockerfile: src/CKO.PaymentGateway.Api/Dockerfile

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5532:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local